version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  auth:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    links:
      - "postgres"
      - "postgres:postgres"
    env_file:
      - ./server/.env

    container_name: auth_server
  
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=saif
      - POSTGRES_PASSWORD=clam
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data
  
  client:
    build: ./client
    ports:
    - "3000:3000"
    


volumes:
  postgres:
    name: postgres
